version: "3.9"
services:
  # web: 
  #   image: nginx:latest
  #   restart: always
  #   volumes:
  #       - ./public:/var/docker/public
  #       - ./config/nginx/conf.d:/etc/nginx/conf.d
  #       - ./certbot/conf:/etc/nginx/ssl
  #       - ./certbot/data:/var/www/certbot
  #   ports:
  #       - 80:80
  #       - 443:443

  # certbot:
  #   image: certbot/certbot:latest
  #   command: certonly --webroot --webroot-path=/var/www/certbot --email zachkadish@gmail.com --agree-tos --no-eff-email -d dev.auth.mongo.overquota.io -d www.dev.auth.mongo.overquota.io
  #   volumes:
  #       - ./certbot/conf:/etc/letsencrypt
  #       - ./certbot/logs:/var/log/letsencrypt
  #       - ./certbot/data:/var/www/certbot

  mongodb-auth:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    command: [--config, '/etc/${MONGO_CONFIG}']
    # command: mongo --config /etc/${MONGO_CONFIG}
    networks:
      - skillup-network
    # networks:
    #   hostnet: {}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${INIT_MONGO_DB}
    volumes:
      - ${ROOT_PATH}/mongo-data:/data/db
      - ${ROOT_PATH}/mongo-scripts/${INIT_MONGO_JS}:/docker-entrypoint-initdb.d/${INIT_MONGO_JS}:ro
    ports:
      - 56702:56702
      # - 80:80 # open port 80 for nginx
    # healthcheck:
    #   test: echo 'db.runCommand("ping").ok' | mongo 127.0.0.1:27017/test --quiet
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    restart: unless-stopped

  mongo-express-auth:
    build:
      context: .
      dockerfile: Dockerfile.mongo-express
    networks:
      - skillup-network
    # networks:
    #   hostnet: {}
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb-auth
      - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD}
    volumes:
      - ${ROOT_PATH}/mongo-data
    depends_on:
      - mongodb-auth
    ports:
      - 8000:8081
    # healthcheck:
    #   test:  wget --quiet --tries=3 --spider http://admin:admin123@0.0.0.0:8081 || exit 1
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    restart: unless-stopped
  
volumes:
  mongo-data:

# networks:
#   hostnet:
#     external: true
#     name: host
  
networks:
  skillup-network:
    external: true
    # name: skillup-network
